### ISSUE TITLE
라이님 질문있습니다. - 14264

### ISSUE THREAD

**Issue by wnghdcjfe** [kks227/BOJ#1]
```c++
#include <cstdio>
#include <cmath>
using namespace std;

int main(){
	int L;
	scanf("%d", &L);
	printf("%.10lf\n", 0.25*L*L*sqrt(3));
}

```
라이님이 푸신 문제중 https://www.acmicpc.net/problem/14264
문제에 대해서인데요. 
저는 `(정육면체의 넓이 - l * l * sin(120)) / 2` 이렇게 4개의 삼각형으로 나눴을 때 오른쪽 왼쪽의 너비를 빼고 1/2를 하는 것으로 생각을 했는데 어떻게 저렇게 깔끔하고 작은 식이 나올 수 있는지 어떻게 푸셨는지 궁금합니다. 
답변부탁드립니다. 감사합니다.

**Comment by kks227** [comment]
안녕하세요. 제가 요즘 바빠서 답장이 많이 늦었는데,
정육각형에 겹치지 않는 3개의 대각선을 그었을때 나오는 제일 좁은 삼각형은 항상 동일한 크기와 형태를 가집니다.
두 변의 길이가 L이고 사잇각이 120도인 삼각형인데요. 그냥 이걸 삼각비 등을 사용해서 면적을 구한 겁니다.

2019년 10월 19일 (토) 오전 8:43, kundol <notifications@github.com>님이 작성:

**Comment by wnghdcjfe** [comment]
아 저게 루트3 / 4라는 뜻이군요. 제가 문제 자체를 이해를 못해서 정육면체에서 뺴는 식으로 생각했네요ㅎㅎ 답변해주셔서 감사합니다!
